"""add foreign key constraint cascade

Revision ID: 773bacb5113f
Revises: 7ec9990ad854
Create Date: 2020-12-27 16:44:36.620218

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '773bacb5113f'
down_revision = '7ec9990ad854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customer_address', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'customer', ['customer_id'], [
                          'id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('fk_customer_address', 'address',
                          'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
