"""add audit table

Revision ID: 8f2c61295047
Revises: 773bacb5113f
Create Date: 2020-12-28 12:41:30.324727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f2c61295047'
down_revision = '773bacb5113f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('table', sa.String(length=50), nullable=True),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('operation', sa.Enum('INSERT', 'UPDATE', 'DELETE', name='operation_enum'), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    # ### end Alembic commands ###
